name: Build and Push Kapinger Image



name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Windows image
        uses: docker/build-push-action@v2
        with:
          context: /hack/tools/kapinger
          file: ./hack/tools/kapinger/Dockerfile.windows
          platforms: windows/amd64
          push: true
          tags: ghcr.io/microsoft/retina/kapinger:windows-${{ github.sha }}

      - name: Build and push Linux image
        uses: docker/build-push-action@v2
        with:
          context: ./hack/tools/kapinger
          file: ./hack/tools/kapinger/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/microsoft/retina/kapinger:linux-${{ github.sha }}

      - name: Create and push manifest
        id: docker_manifest
        run: |
          docker manifest create ghcr.io/microsoft/retina/kapinger:latest ghcr.io/microsoft/retina/kapinger:windows-${{ github.sha }} ghcr.io/microsoft/retina/kapinger:linux-${{ github.sha }}
          docker manifest push ghcr.io/microsoft/retina/kapinger:latest
